name: create_tone_job

on:
  push:
    branches:
      - main
    
jobs:
  create_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create T-One Job
        uses: shankailun-aliyun/T-One@main
        with:
          username: shankailun10
          token: 43be8d4ce6f1425986c658ad68a4ec47
          workspace: platform_test
          template: create_job_template
